crx_v1:
  joint_a2b_position_controller:
    type: position_controllers/JointPositionController
    joint: link_A_to_link_B
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_a2b_effort_controller:
    type: effort_controllers/JointPositionController
    joint: link_A_to_link_B
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_b2c_position_controller:
    type: position_controllers/JointPositionController
    joint: link_B_to_link_C
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint_b2c_effort_controller:
    type: effort_controllers/JointPositionController
    joint: link_B_to_link_C
    pid: {p: 100.0, i: 0.01, d: 10.0}